driver/urls.py
from django.urls import path
from . import views


app_name = 'driver'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail')
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include


admin.site.site_title = 'ドライバー管理システム'
admin.site.site_header = 'ドライバー管理システム' 
admin.site.index_title = 'メニュー'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('driver.urls')),
]

driver/models.py
from django.db import models
from django.utils import timezone


GENDER_CHOICES = [
    ('1', '男性'),
    ('2', '女性'),
]


class Course(models.Model):
    name = models.CharField('コース', max_length=255)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name

        
class Company(models.Model):
    name = models.CharField('会社名', max_length=255, default='ティートレジャー')
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class Driver(models.Model):
    name = models.CharField('名前', max_length=20)
    age = models.IntegerField('年齢', blank=True)
    gender = models.CharField("性別", max_length=2, choices=GENDER_CHOICES, blank=True)
    phone = models.CharField("電話番号", max_length=255, blank=True)
    course = models.ManyToManyField(
        Course, verbose_name='コース'
    )
    company = models.ForeignKey(
        Company, verbose_name='会社名', on_delete=models.PROTECT, default='T'
    )
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return f'{self.name}　 電話番号：{self.phone}'

driver/views.py
from django.db.models import Q
from django.views import generic
from .models import Driver


class IndexView(generic.ListView):
    model = Driver
    paginate_by = 15

    def get_queryset(self):
        queryset = Driver.objects.all()
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(name__icontains=keyword)| Q(company__name__icontains=keyword)
            )

        return queryset


class DetailView(generic.DetailView):
    model = Driver

driver/templates/driver/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>ドライバー管理システム</title>
  </head>
  <body>
  {% if not user.is_active %}
  <h3 style="text-align: center;">こちらから<a href="admin/">管理サイト</a>へログインしてください</h3>
  {% endif %}
  {% if user.is_active %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ドライバー管理システム</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'driver:index' %}">一覧 <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:driver_driver_add' %}" target='_brank'>ドライバー追加</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'driver:index' %}">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endif %}
  </body>
</html>

driver/templates/driver/driver_detail.html
{% extends 'driver/base.html' %}

{% block content %}
<ul class="list-group mt-5">
    <li class="list-group-item">会社：{{ driver.company }}</li>
    <li class="list-group-item">{{ driver.name }}</li>
    <li class="list-group-item">{{ driver.age }}歳</li>
    <li class="list-group-item">{{ driver.get_gender_display }}</li>
    <li class="list-group-item">電話番号：{{ driver.phone }}</li>
    <li class="list-group-item">コース：{% for course in driver.course.all %}{{ course }}, {% endfor %}</li>  
</ul>
{% endblock %}

driver/templates/driver/driver_list.html
{% extends 'driver/base.html' %}

{% block content %}
<table class="table mt-3">
  <thead class="thead-dark">
    <tr>
      <th>会社名</th>
      <th>名前</th>
      <th>電話番号</th>
      <th>コース</th>
    </tr>
  </thead>
  <tbody>
    {% for driver in driver_list %}
    <tr>
      <td>{{ driver.company }}</td>
      <td><a href="{% url 'driver:detail' driver.pk %}">{{ driver.name }}</a></td>
      <td>{{ driver.phone }}</td>
      <td>{% for course in driver.course.all %}{{ course }}, {% endfor %}</td>  
    </tr>
    {% endfor %}
  </tbody>
</table>

{% include 'driver/page.html' %}

{% endblock %}

driver/templates/driver/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>